// src/dummydata/serviceProviders.ts
import { ServiceProvider, CategoryInfo } from '../types/collaborators';

export const categoryData: CategoryInfo[] = [
  { id: 'health', name: 'Health', icon: '🏥', color: '#10B981' },
  { id: 'home', name: 'Home', icon: '🏠', color: '#3B82F6' },
  { id: 'finance', name: 'Finance', icon: '💼', color: '#8B5CF6' },
  { id: 'legal', name: 'Legal', icon: '⚖️', color: '#EF4444' },
  { id: 'auto', name: 'Auto', icon: '🚗', color: '#F59E0B' },
  { id: 'education', name: 'Education', icon: '📚', color: '#EC4899' },
  { id: 'other', name: 'Other', icon: '🎯', color: '#6B7280' },
];

export const dummyServiceProviders: ServiceProvider[] = [
  {
    id: 'sp1',
    name: 'Dr. Rajesh Sharma',
    category: 'health',
    specialization: 'Family Doctor',
    phone: '+91-98765-43210',
    email: 'dr.sharma@healthcare.com',
    isBookmarked: true,
    isExternal: false,
    lastContacted: new Date('2024-10-18'),
    notes: 'Available on weekends, very experienced',
  },
  {
    id: 'sp2',
    name: 'Dr. Priya Menon',
    category: 'health',
    specialization: 'Pediatrician',
    phone: '+91-98765-43211',
    email: 'dr.priya@childcare.com',
    isBookmarked: true,
    isExternal: false,
    lastContacted: new Date('2024-10-25'),
    notes: 'Great with children',
  },
  {
    id: 'sp3',
    name: 'Ravi Plumbing Services',
    category: 'home',
    specialization: 'Plumber',
    phone: '+91-98765-43212',
    isBookmarked: true,
    isExternal: false,
    lastContacted: new Date('2024-10-20'),
    notes: 'Quick response time, fair pricing',
  },
  {
    id: 'sp4',
    name: 'Kumar Electricals',
    category: 'home',
    specialization: 'Electrician',
    phone: '+91-98765-43213',
    email: 'kumar@electricals.com',
    isBookmarked: false,
    isExternal: false,
    lastContacted: new Date('2024-09-15'),
  },
  {
    id: 'sp5',
    name: 'CA Suresh Kumar',
    category: 'finance',
    specialization: 'Chartered Accountant',
    phone: '+91-98765-43214',
    email: 'suresh@caservices.com',
    isBookmarked: true,
    isExternal: false,
    lastContacted: new Date('2024-10-30'),
    notes: 'Tax filing and financial planning',
  },
  {
    id: 'sp6',
    name: 'Wealth Advisors Inc',
    category: 'finance',
    specialization: 'Financial Advisor',
    phone: '+91-98765-43215',
    email: 'contact@wealthadvisors.com',
    isBookmarked: false,
    isExternal: true,
    notes: 'Investment planning and portfolio management',
  },
  {
    id: 'sp7',
    name: 'Adv. Lakshmi Iyer',
    category: 'legal',
    specialization: 'Family Lawyer',
    phone: '+91-98765-43216',
    email: 'lakshmi@legalservices.com',
    isBookmarked: true,
    isExternal: false,
    lastContacted: new Date('2024-08-10'),
  },
  {
    id: 'sp8',
    name: 'Auto Care Center',
    category: 'auto',
    specialization: 'Car Mechanic',
    phone: '+91-98765-43217',
    isBookmarked: true,
    isExternal: false,
    lastContacted: new Date('2024-10-28'),
    notes: 'Regular servicing, trusted mechanic',
  },
  {
    id: 'sp9',
    name: 'Painting Masters',
    category: 'home',
    specialization: 'Painter',
    phone: '+91-98765-43218',
    isBookmarked: false,
    isExternal: false,
  },
  {
    id: 'sp10',
    name: 'Learn & Grow Academy',
    category: 'education',
    specialization: 'Tutor - Mathematics',
    phone: '+91-98765-43219',
    email: 'info@learngrow.com',
    isBookmarked: true,
    isExternal: true,
    lastContacted: new Date('2024-10-15'),
  },
];
